#!/bin/sh
mount -t debugfs none /sys/kernel/debug  2>/dev/null
cd /sys/kernel/debug/tracing
echo 100000 > buffer_size_kb
echo nop > current_tracer
#  exemple for also tracing all function starting with hsi:
#  echo function > current_tracer
#  echo hsi* >> set_ftrace_filter
echo 0 > tracing_enabled
echo > set_event
echo sched:* >> set_event
# echo cpufreq_interactive:* >> set_event
# echo sched:sched_wakeup >> set_event
# echo sched:sched_switch >> set_event
echo timer:timer_init >> set_event
echo timer:timer_start >> set_event
echo timer:timer_expire_entry >> set_event
echo timer:timer_expire_exit >> set_event
echo timer:hrtimer_start >> set_event
echo timer:hrtimer_expire_entry >> set_event
echo timer:hrtimer_expire_exit >> set_event
echo timer:itimer_expire >> set_event
echo workqueue:workqueue_execution >> set_event
echo workqueue:workqueue_execution_end >> set_event
echo workqueue:workqueue_execute >> set_event
echo workqueue:workqueue_execute_end >> set_event
echo power:* >> set_event
echo irq:* >> set_event

echo >trace
echo 1 >tracing_enabled
